"""CONSTANT VARS"""

CLOCK_TICK = 0.2  # GAME TIMER TICK IN SECONDS

BLOCK_SIZE = 20
LENGTH_X_Y = 600  # change LENGTH_X_Y as you like

LIMIT_X_Y = (LENGTH_X_Y / 2) - BLOCK_SIZE
BOUNDARY_X_Y = LENGTH_X_Y / 2

BOUNDARY_COLOR = "#483D8B"  # DARK SLATE BLUE
SOFT_HIT_COLOR = "#FFFAFA"  # SNOW

SNAKE_HEAD_COLOR = "#DA70D6"  # ORCHID
SNAKE_BODY_COLOR = "#DDA0DD"  # PLUM
SNAKE_HT_COLOR = "#FF4500"  # ORANGE RED
SNAKE_SHAPE = "square"

FOOD_COLOR = "#FF00FF"  # MAGENTA
FOOD_SHAPE = "circle"
FOOD_SIZE = 0.52
